import {
  attribute,
  autoGeneratedHashKey,
  table,
} from '@aws/dynamodb-data-mapper-annotations';

@table(process.env.DDB_TABLE_NAME_ASSETS as string)
export default class Asset {
  @autoGeneratedHashKey()
  public id: string;

  @attribute()
  public prefix: string;

  @attribute()
  public creatorId: string;

  @attribute()
  public key: string;

  @attribute()
  public name: string;

  @attribute()
  public contentType: string;

  @attribute()
  public serverCreatedAt: string;

  @attribute()
  public serverUpdatedAt: string;

  @attribute()
  public caption: string | null;
}
